#!/bin/sh

uci -q set wireless.radio0.disabled='1'
uci -q set wireless.radio1.disabled='1'
uci -q set wireless.default_radio0.disabled='1'
uci -q set wireless.default_radio1.disabled='1'
uci -q commit wireless

exit 0

